### Server Properties

host: 0.0.0.0
# ONLY CHANGE THIS IF YOU KNOW WHAT YOU'RE DOING!
# Defines what IP YarnMC should bind to.

port: 19132
# ONLY CHANGE THIS IF YOU KNOW WHAT YOU'RE DOING!
# Defines what port YarnMC should bind to.

world: none
# Defines what world the server should use. Set to "none" to not use a world; this means that chunk loading will not work, and players will be unable to move.

offline: false
# Defines whether the server should be in offline mode (you don't need an XBOX account to join) or not.

maxPlayerCount: 10
# Defines how many players can be on the server online.

version: 1.19.60
# This version will be the version that clients can connect to.

motd: Hello
# Message to shoe beneath the server name.

### Terminal Settings

chatLog: true
# Decides whether all chat messages should be logged onto the terminal.

joinLog: true
# Decides whether all player joins and leaves should be logged onto the terminal.